ORIGINAL_TEXTS = {
    '001': 'JAIR NICOLAS RODRIGUEZ OSORIO',
    '002': 'YULI PAOLA NARANJO MUÑOZ',
    '003': 'MANUEL ALFONSO MORENO LOPEZ',
    '004': 'LINA CARELY BARON BOHORQUEZ',
    '005': 'LINA FERNANDA URRUTIA LARA',
    '006': 'IVAN DARIO RAMIREZ GUTIERREZ',
    '007': 'JUAN JAVIER ALFONSO RODRIGUEZ',
    '008': 'ANDRES FELIPE VERGARA MARTINEZ',
    '009': 'LEIDY MARCELA SOTELO TORRES',
    '010': 'JENNIFER ALEJANDRA MOGOLLON DE ANTONIO',
}
