#!/usr/bin/env bash
star() {
    cd ..
    source env/bin/activate
    pip install -r requirements.txt
}

star-app() {
    cd ..
    python app.py
}

star-api() {
	cd ..
    python api.py
}

# Start
start
star-app
star-api