#!/usr/bin/env bash
start() {
    cd ..
    source env/bin/activate
    pip install -r requirements.txt
}

start-app() {
    python app.py
}

start-api() {
    python api.py
}

# Start
start
start-app
start-api